package com.boatit.boatsharing.network.di

object ApiConstants {
    const val BASE_URL = "https://testbyfarhan.squarecod.com/api"
    object Endpoints {
        const val LOGIN = "/Account/Login"
        const val REFRESH = "/Account/RefreshToken"
        const val ROLE = "/Account/UpdateRole"
        const val FCMToken = "/Account/UpdateDeviceToken"
        const val REGISTER = "/Account/Register"
        const val FORGOTPASS = "/Account/ForgotPassword"
        const val VERIFY = "/RegistrationTemp/Verify"
        const val ADD = "/RegistrationTemp/Add"
        const val DOCK = "/Dock/GetActive"
        const val FIND_BOAT = "/Voyage/FindBoat"
        const val SAVE_VOYAGER_PROFILE = "/VoyagerProfile/Save"
        const val GET_VOYAGER_PROFILE = "/VoyagerProfile/GetByUserId"
        const val SAVE_CAPTAIN_PROFILE = "/CaptainProfile/Save"
        const val GET_CAPTAIN_PROFILE = "/CaptainProfile/GetByUserId"
        const val SAVE_BUSINESS_PROFILE = "/BusinessProfile/Save"
        const val GET_BUSINESS_PROFILE = "/BusinessProfile/GetByUserId"
        const val SAVE_BUSINESS_INFO_PROFILE = "/BusinessInfo/Save"
        const val GET_BUSINESS_INFO_PROFILE = "/BusinessInfo/GetByUserId"
        const val SAVE_BUSINESS_ABOUT = "/BusinessInfo/SaveAbout"
        const val SAVE_BUSINESS_LOGO = "/BusinessInfo/SaveLogo"
        const val SAVE_CAPTAIN_BOAT = "/CaptainBoat/Save"
        const val UPDATE_CAPTAIN_STATUS = "/CaptainProfile/Availability"
        const val ACCEPT_REQUEST = "/Voyage/Accept"
        const val START_VOYAGE = "/Voyage/Start"
        const val COMPLETE_VOYAGE = "/Voyage/Complete"
        const val CANCEL_VOYAGE = "/Voyage/Cancel"
        const val PAYMENT = "/Voyage/Payment"
        const val GET_CAPTAIN_BOAT = "/CaptainBoat/GetByUserId"
        const val SAVE_CAPTAIN_DOCS = "/CaptainDocument/Save"
        const val GET_CAPTAIN_DOCS = "/CaptainDocument/GetByUserId"
        const val GET_CAPTAIN_VOYAGES = "/CaptainDashboard/GetVoyages"
    }
}